image: node:16.13.2 # @apollo/federation@0.27.0: The engine "node" is incompatible with this module. Expected version ">=12.13.0 <17.0". Got "17.4.0"

.node_modules-cache: &node_modules-cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
  policy: pull

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

# https://docs.gitlab.com/ee/ci/merge_request_pipelines/
.only-default: &only-default
  only:
    - web
    - pushes
    - merge_requests
    - tags

stages:
  - deploy
  - test

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

deploy:
  stage: deploy
#  only:
#    - main
  before_script:
    - npm ci --cache .npm --prefer-offline
    - echo "//gitlab.example.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
  script:
    - npm publish
  cache:
    - <<: *node_modules-cache
      policy: pull-push
